development:
  adapter: postgresql
  encoding: unicode
  database: theplantaeapi_development
  pool: 5
  username:
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: theplantaeapi_production
  pool: 5
  username:
  password:
  host: localhost
